sudo: required
dist: trusty
language: cpp

os:
  - linux

addons:
  apt:
    packages: ['zlib1g-dev', 'libbz2-dev', 'libsnappy-dev', 'curl', 'libprotobuf-dev', 'protobuf-compiler', 'libgoogle-glog-dev']

compiler:
  - gcc

language: cpp

script:
  - git submodule init
  - git submodule update
  - make PROCESSOR_NUMS=2
